### PR TITLE
Mobile version

### PR DESCRIPTION
**Pull request by kosher9**
- Added projects section
- Added about me section
- Added contact me section

### CODE REVIEW

**Review by Lordkaito — CHANGES_REQUESTED** [review]
Hi @kosher9,

 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kosher9** [comment]
Hi @Lordkaito. I think I made all the changes needed. Please, can you check my code ?

**Comment by Lordkaito** [comment]
Hi @kosher9. Good to know you applied changes!

If you think you are done please go ahead an ask for a new review from your dashboard so a code reviewer can take your PR and check it! 

_Note: Remember not to open a new PR, just use the same link that you used earlier to ask for a new review_ 

Good luck!

**Review by codepantherr — CHANGES_REQUESTED** [review]
### Hi @kosher9 👋, 

I commend you for implementing some of the changes requested by the previous reviewer 👏 👏 
There is one final issue that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes ♻️ 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] Kindly fix the horizontal scrolling on the mobile version of your portfolio. You have done a great job and fixing this will improve user experience. 👍 
image

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by Wes-Isaac — APPROVED** [review]
Hi @kosher9 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
